# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a6dadfec9cde09886dc04304fa2d27d0321d9f9483210fb77a2276c78114b5c72ece4e8d6063b63242b53abac945da0bb94b2071479770056007c2300c3d952

test:
  secret_key_base: f412e6a995fdc4948a2842f6733271f738af5ba303a2e10da7441d6a66c25d38fdc7e7f23a35f08657e69525bd30d20bb2999c3dd4fcfe5d7f64d66fdc220f6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
